name: lunar-traveler
dependencies:
  - python=3.7
  - pip=19.1.1
  - jupyter=1.0.0
  - matplotlib=3.0.3
  - seaborn=0.9.0
  - plotly=3.10.0
  - scipy=1.3.0
  - pandas==1.1.2
  - numpy==1.19.2
  - bcrypt=3.2.0
  - setuptools=52.0.0
  - pip:
      - cryptography==2.8
      - microsoft-bonsai-api==0.1.3
      - msal==1.14.0
      - bonsai-cli==1.0.16
      - azure-cli==2.29.0
      - azure-batch==11.0.0 #batch requirement
      - cufflinks==0.16
      - vpython==7.6.0
      - pyglet==1.5.0
      - jinja2==2.11.2
      - python-dotenv==0.13.0
      - typer==0.2.1
      - Kqlmagic==0.1.113.post1
      - pytest==6.0.1
      - gym==0.26.0
      # Batch packages
      - beautifulsoup4==4.9.1
      - bitstring==3.1.7
      - blobxfer==1.9.2
      - fire==0.2.1
      - rich==9.3.0
      
